---
SHOW_ELAPSED_TIME: true
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - JSON_PRETTIER
DOCKERFILE_HADOLINT_FILE_NAMES_REGEX:
  - "^Dockerfile(\\.[a-zA-Z0-9_-]+)?$"
