---
name: Bug Report
description: Report a bug.
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Summary
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we reproduce it?
    validations:
      required: true

  - type: textarea
    attributes:
      label: OS
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version of docker
      placeholder: 'docker version'
      render: text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs and errors
      render: text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else we need to know
