---
name: Enhancement Request
description: Request a new feature.
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: What would you like to be added
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is this needed
    validations:
      required: true
